### ISSUE TITLE
Wallpaper: Background wall turns black when the source image is deleted

### ISSUE THREAD

**Issue by Rezonansowy** [linuxmint/cinnamon-control-center#102]
Background image should be copied somewhere to prevent black screen.

**Comment by Vahan86** [comment]
Can't reproduce this in Cinnamon 3.0.7. Desktop background stays the same when the source image is deleted.

@Rezonansowy, is this still an issue for you in Cinnamon 3.0?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by leigh123linux** [comment]
cinnamon-control-center doesn't control the background settings, the code for that is in cinnamon.

@Rezonansowy 
cinnamon-settings background has the ability to add new folders to watch, I suggest in future you add a ~/.backgrounds directory and use it.

**Comment by Rezonansowy** [comment]
@leigh123linux OK, thanks for your hint.
