### ISSUE TITLE
mintLocale doesnt allow me to set numeric format

### ISSUE THREAD

**Issue by philipzae** [linuxmint/cinnamon-control-center#106]
I live in the United Arab Emirates and after installing Linux Mint 17 the Languages dialog in Control Panel put my region as ar_AE.UTF8. This is all fine except that it shows numbers in arabic which i dont want to see as i'm a canadian and the dialog doesnt give me an option to fix this.

I ended up having to edit /etc/default/locale and setting LC_NUMERIC as "en_US.UTF-8" to solve this problem. It would be nice if there were a means of solving this problem within the GUI app.

**Comment by GLolol** [comment]
You might want to report this at [linuxmint/mintLocale](https://github.com/linuxmint/mintLocale), since it's maintained separately there.

**Comment by philipzae** [comment]
Will do.
