### ISSUE TITLE
Network Time option no longer works.

### ISSUE THREAD

**Issue by lots0logs** [linuxmint/cinnamon-control-center#108]
```
datetime-cc-panel-WARNING **: Could not set system to use NTP: GDBus.Error:org.cinnamon.SettingsDaemon.DateTimeMechanism.GeneralError: Error enabling NTP: OS variant not supported
```
Arch Linux: Kernel 3.18.6
Cinnamon: 2.4.6
Cinnamon Control Center: 2.4.2

Please let me know if any further information is needed. Thanks!

**Comment by leigh123linux** [comment]
cinnamon-settings-daemon (or gnome-settings-daemon) has never supported arch linux.

https://github.com/linuxmint/cinnamon-settings-daemon/tree/master/plugins/datetime

Your issue will need to be addressed by the arch linux cinnamon developer and not here!

**Comment by clefebvre** [comment]
It looks like this is pretty distro-specific alright. We can add support for Arch, but we would need a dev. running Arch to port the feature first. Look in https://github.com/linuxmint/cinnamon-settings-daemon/tree/master/plugins/datetime, see how there are implementations for SUSE, Debian and Fedora? We'd need something similar for Arch Linux.

**Comment by lots0logs** [comment]
I'm not sure what caused the issue but it appears to be resolved. It began working properly again a few days ago. Sorry I didnt update the gh issue before now :sweat_smile:
