### ISSUE TITLE
Networking applet initializes with the wrong window size

### ISSUE THREAD

**Issue by jlu5** [linuxmint/cinnamon-control-center#116]
Whenever the Networking applet is launched from the application menu, a desktop shortcut, or system settings (the latter only the first time), the Networking applet initializes with the wrong window size. It should be big enough to display the entire window contents without manually resizing.

![](https://dl.dropboxusercontent.com/u/18664770/ccc-wrongwindowsize.png)

**Comment by Vahan86** [comment]
It works fine for me in Cinnamon 3.0.7.

@GLolol, is this still an issue for you with Cinnamon 3.0?

**Comment by GLolol** [comment]
Still happening for me: cinnamon-control-center 3.0.1-1 and cinnamon 3.0.7-1 from Debian testing/unstable

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a bug?

**Comment by JosephMcc** [comment]
Sure, though I can't reproduce it on Mint 18 running cinnamon from git.

**Comment by icarter09** [comment]
Mint 19.3
Cinnamon-control-center 4.6.0

I'm not able to reproduce this issue either.
