### ISSUE TITLE
new design: selection buttons not always in sync with settings window

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-control-center#120]
Cinnamon 2.6.7, LM 17.1 64-bit
1. all settings
2. choose effects (e.g.)
3. click button "customize"
4. click arrow "back to all settings"
5. choose applets (e.g.)
6. click arrow "back to all settings"
7. choose effects again
-> button "enable effects" is active, but the last chosen window "customize" is shown

**Comment by VolMi** [comment]
For me (2.6.7, on Debian), after step 7, "enable effects" is inactive. "customize" is active and shown.

**Comment by Mintulix** [comment]
Hi VolMi, your are right, LMDE Betsy seems to be ok. Rebecca with 2.6.7 and Rafaela RC with 2.6.8 are not ok (all 64 bit).
