### ISSUE TITLE
Availability to rename Sound In/Outputs

### ISSUE THREAD

**Issue by tedr56** [linuxmint/cinnamon-control-center#122]
Just a small but great enhencement would be the possibility to rename Sound In/Outputs.
It would be a lot easier for systems with a lot of them.

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
