### ISSUE TITLE
No option for Play/Pause in Keyboard Shortcuts

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/cinnamon-control-center#125]
Under the Sound and Media section of the Keyboard Shortcuts settings screen, there is no option for "Play/Pause," only "Play" and "Pause". Many keyboards have a single key for play/pause, and it cannot be assigned to both actions.

Mint 17.2 Cinnamon (2.6)

**Comment by mtwebster** [comment]
I looked into this briefly.. most players perform Play/Pause when the key assigned to Play is hit repeatedly - at least all of the ones I checked.  So, if Play is not assigned in your shortcut list, just assign the Play/Pause key to it.  If you encounter any players that don't support this, I'd try to bring it up with their developers.  If that goes no-where, mention it here, we might be able to work around specific cases.

Closing this for now.
