### ISSUE TITLE
Screensaver and power settings relationship

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon-control-center#149]
There is the obvious relationship between the time-out settings for the screensaver and for turning off the monitor / auto-switching to suspend after the time inactivity. Those settings are out of obvious reasons in different dialogs.

IIRC there was in Mint 13 a link to switch to the other dialog, which was very convenient.
Please restore this link (for both directions) again.

**Comment by JosephMcc** [comment]
There is a completely rewritten screensaver already in git master for Cinnamon 3.2. I think the settings are going to get some revamping tweaking because this has been brought up by users a number of times.
