### ISSUE TITLE
Cinnamon should not offer lid suspend management if systemd is enabled to provide them

### ISSUE THREAD

**Issue by marmistrz** [linuxmint/cinnamon-control-center#154]
If systemd handle the lid actions, the Cinnamon actions will have no effect.

**Comment by jonorthwash** [comment]
I'm having this same issue on Debian unstable, with a recent upgrade to Cinnamon 3.2.7 (as part of a full ~monthly dist-upgrade).  With older versions of Cinnamon, my system would suspend on lid close, regardless of Cinnamon's power settings (i.e., set to "do nothing"), but then it worked correctly for a number of versions (i.e., didn't suspend on lid close).  But on this recent dist-upgrade, it stopped working again.  Perhaps a reversion?

Please let me know if any particular information would be useful for debugging this.

**Comment by leigh123linux** [comment]
Please refile the issue against cinnamon as it has the power settings code.

https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py

**Comment by marmistrz** [comment]
Cinnamon settings daemon is the culprit here. It inhibits the systemd pm.

I started working on it but was too busy. I hope I manage to do that in February. It's not a big change, after all.

My change will add a dconf key to use the systemd pm instead of the cinnamon one.

On February 4, 2017 8:24:54 AM GMT+01:00, leigh123linux <notifications@github.com> wrote:
>Please refile the issue against cinnamon as it has the power settings
>code.
>
>https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/linuxmint/cinnamon-control-center/issues/154#issuecomment-277425614

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
