### ISSUE TITLE
Accessibility: High contrast deactivation sets mint-x even if another theme has been set before

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon-control-center#161]
How to reproduce:
- Start `cinnamon-settings` 
- Click Themes and choose a theme that is not Mint-X
- Go back and click on Accessibility.
- Select `High contrast` to activate it, deactivate it afterwards

Now, Mint-X is set as theme and not the theme that you have chosen before.

**Comment by JosephMcc** [comment]
Without looking at code at all, I would assume that it's just resetting defaults. That would explain why it gives you Mint-X. You could probably save the old theme in memory but it wouldn't persist across a restart. To change it you would probably have to completely change how it works.

**Comment by Piiit** [comment]
I see, still it is an issue because it is not intuitive for users IMHO. I suggest to change it, s.t., it stores previously selected theme options and restores them after deactivating "High contrast".

**Comment by Piiit** [comment]
Checked https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/cinnamon-settings/modules/cs_accessibility.py.

You were right, it resets to defaults.

**Comment by mtwebster** [comment]
This was fixed: https://github.com/linuxmint/Cinnamon/pull/6415/commits/b437a2d188261fd46b168213f2a8e2850caa2e7f
