### ISSUE TITLE
[Feature request] Port libnm-glib code to new libnm-api

### ISSUE THREAD

**Issue by besser82** [linuxmint/cinnamon-control-center#164]
libnm-glib is deprecated since NetworkManager 1.2; most up2date distros ship NetworkManager 1.2 / 1.4.  Cinnamon-control-center still uses the legacy glib-api.

If the legacy api will fade, VPN-connection will be broken.

There might be needed adkustment for cinnamon and cinnamon-settings-daemon, too.

See: https://bugzilla.redhat.com/show_bug.cgi?id=1413610

Cheers
  Björn

**Comment by jbicha** [comment]
@clefebvre I believe you can close this issue since the PR was merged in cinnamon-control-center 3.6
