### ISSUE TITLE
Settings window's search field not translated

### ISSUE THREAD

**Issue by Piiit** [linuxmint/cinnamon-control-center#172]
![bildschirmfoto vom 2017-05-09 13-28-03](https://cloud.githubusercontent.com/assets/6096063/25848828/5d61e414-34bc-11e7-94cf-8e32050f03ec.png)

"Search..." text is not translated.

**Comment by leigh123linux** [comment]
@Piiit  The screenshot shows cinnamon-settings not part of cinnamon-control-center

I believe you should file the issue against cinnamon or translations.

P.S Sorry for closing you misfiled issue

**Comment by Piiit** [comment]
@leigh123linux ok, moved it to linuxmint/Cinnamon#6697
