### ISSUE TITLE
[Bug] Big User Pictures cause the Cinnamon Settings Users window to become bigger than the screen

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-control-center#174]
What the title says, unlike Account Details, this one has the user picture box resize to the image size, which can lead up to awkward situations like this:
![screenshot from 2017-06-07 07-55-57](https://user-images.githubusercontent.com/11057934/26865917-c4737b58-4b56-11e7-82d3-4f854991644f.png)

**Comment by leigh123linux** [comment]
cinnamon-settings is part of cinnamon

**Comment by feren** [comment]
Oh. Shall I post it on Cinnamon's bug tracker then @leigh123linux ?

**Comment by leigh123linux** [comment]
yes

**Comment by feren** [comment]
@leigh123linux https://github.com/linuxmint/Cinnamon/issues/6588
