### ISSUE TITLE
Font dependant rendering settings

### ISSUE THREAD

**Issue by cmrdt** [linuxmint/cinnamon-control-center#176]
a lot of the fonts are of variable/inconsistent style/quality, 
perhaps enable hinting/contrast/gamma settings
rulesets/logic
e.g. `full hinting` for this `font-family` `regular-weight` when @ size `6.5` to `15` pt, 
- maybe exception for certain specific sizes
- fonts that look very different if @ certain integer sizes (blurry/sharp..)

**Comment by JosephMcc** [comment]
Ah, no. Every user has a different opinion on what "looks good".

**Comment by cmrdt** [comment]
no it doesnt have to be universal for all users, didnt say clearly
even windows font smoothing has options
 in settings due to preferences
