### ISSUE TITLE
Show applications of all workspaces in panel

### ISSUE THREAD

**Issue by bittner** [linuxmint/cinnamon-control-center#179]
I'm using Cinnamon Desktop 3.2 (on Ubuntu 17.04, but that shouldn't matter) with several workspaces.

When I switch to a workspace only the applications of that workspace are displayed in the panel on the bottom of the screen. I'd like to have all applications of all workspaces be listed in the panel all the time, so that I can easily switch to a running instance of, say, the web browser or terminal window.

This problem is described [on StackExchange](https://unix.stackexchange.com/questions/61241/showing-all-open-apps-in-all-workspaces-on-the-desktop-panel-for-linux-mint) for the XFCE desktop. I couldn't find that solution in the current version of Cinnamon's _System Settings_, though.

Only on Window-by-Window Basis
-----------

The only way I can currently fix this issue for me is on a window-by-window basis, by selecting _Always on Visible Workspace_ from the context menu (on the title bar) of any application window. However, this is tedious and a recurring, manual activity.

Any hint for a solution? Is this not yet possible? (i.e. should I convert this question into a feature request?)

**Comment by OlVerm** [comment]
Got exactly the same question ! Someone can answer this issue ?
Thanks a lot !

**Comment by OlVerm** [comment]
I asked the same question on the Linux Mint forum, here are some answers : [https://forums.linuxmint.com/viewtopic.php?f=208&t=262017&p=1417292#p1417292](https://forums.linuxmint.com/viewtopic.php?f=208&t=262017&p=1417292#p1417292)
I haven't found the perfect way of doing it, but there are some good suggestions there !

**Comment by JosephMcc** [comment]
This should be configurable from the window list applet. There is an option in it's settings to "Show windows on all workspaces".

**Comment by OlVerm** [comment]
Hi JosephMcc,
This option doesn't exist in my window list applet :-/
I've got only this :
![window list applet](https://user-images.githubusercontent.com/35571780/35437831-72caf394-0294-11e8-83e8-009fb2832f90.png)

any idea ho to add this option to the applet ?

thanks a lot !

**Comment by JosephMcc** [comment]
It was added in Cinnamon 3.6. You don't say what version you're using.
