### ISSUE TITLE
Display: dragging display icons is FUBAR

### ISSUE THREAD

**Issue by n1ywb** [linuxmint/cinnamon-control-center#182]
Package: cinnamon-control-center
Version: 3.4.0+sonya

For as long as I can remember, across several years, several major Mint releases, and several computers, I have found that dragging around display icons in the display settings just does not work very well if at all.

E.g. today I connected my new laptop with fresh cinnamon install to two external monitors and closed the lid and turned on both external monitors and tried to arrange them and this happened 

![image](https://user-images.githubusercontent.com/316961/32281988-c752ab5a-bef6-11e7-9ffe-602c45da2f7e.png)

Now when I try to drag any of the monitors they are very 'sticky'; IE they do not want to move; and when they do move, they immediately snap to crazy places 

![image](https://user-images.githubusercontent.com/316961/32282032-e62a4f42-bef6-11e7-8246-1016d1ccd4dc.png)

![image](https://user-images.githubusercontent.com/316961/32282075-fbca12ce-bef6-11e7-971d-04f537cb1b61.png)

it's pretty broken, been this way for a while

**Comment by n1ywb** [comment]
I deleted my .config/monitors.xml file and started over and very carefully arranged them and it worked, this time... but I have seen the above behavior over and over and over.

**Comment by kantlivelong** [comment]
I also experience this behavior. It's easily repeatable by deactivating two of the three, closing, then finally re-opening and trying again.

**Comment by icarter09** [comment]
@n1ywb @kantlivelong are either of you still experiencing this issue?

**Comment by kantlivelong** [comment]
@icarter09 Using Cinnamon 4.4.8 I'm not seeing the issue at this time.
