### ISSUE TITLE
cinnamon-settings network --> can't open vpn editor

### ISSUE THREAD

**Issue by presianbg** [linuxmint/cinnamon-control-center#183]
* Cinnamon version Cinnamon 3.4.6
 * Distribution - Arch
 * Graphics hardware *and* driver used - NVIDIA + linux-ck
 * 64 bit

Issue
```
arch:~$ cinnamon-settings network

** (cinnamon-settings.py:26778): CRITICAL **: file properties/nm-openvpn-editor.c: line 480 (openvpn_editor_new): should not be reached
```

Steps to reproduce

Open network setting and try to edit openvpn config

Expected behaviour

to open openvpn config

Other information
```
arch:~$ pacman -Q | grep network
glib-networking 2.54.1-1
network-manager-applet 1.8.7dev+3+g3d7c0a89-1
networkmanager 1.8.4-1
networkmanager-openvpn 1.8.1dev+10+ge4d8cda-1
networkminer 2.2-1
```

**Comment by besser82** [comment]
This is related to not having `NetworkManager-openvpn-gnome` installed.  The editor cannot be properly loaded, because `/usr/lib64/NetworkManager/libnm-vpn-plugin-openvpn-editor.so` is missing.

**Comment by presianbg** [comment]
It's not missing.
There is symlink lib64 > lib:

.../lib64/NetworkManager$ lc

  rwxr-xr-x    root   41 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-adsl.so
  rwxr-xr-x    root   93 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-bluetooth.so
  rwxr-xr-x    root   61 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-ovs.so
  rwxr-xr-x    root   49 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-team.so
  rwxr-xr-x    root  141 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-wifi.so
  rwxr-xr-x    root   37 KiB  Fri Nov 10 23:16:52 2017  
libnm-device-plugin-wwan.so
  rwxr-xr-x    root  178 KiB  Thu Oct  5 12:55:19 2017  
libnm-openvpn-properties.so
  rwxr-xr-x    root   41 KiB  Fri Nov 10 23:16:52 2017  
libnm-ppp-plugin.so
  rwxr-xr-x    root   21 KiB  Fri Nov 10 23:16:52 2017  
libnm-settings-plugin-ibft.so
  rwxr-xr-x    root  138 KiB  Thu Oct  5 12:55:19 2017  
*libnm-vpn-plugin-openvpn-editor.so *
  rwxr-xr-x    root   53 KiB  Thu Oct  5 12:55:19 2017  
libnm-vpn-plugin-openvpn.so
  rwxr-xr-x    root   73 KiB  Fri Nov 10 23:16:52 2017    libnm-wwan.so
  rwxr-xr-x    root    9 KiB  Fri Nov 10 23:16:52 2017    nm-dhcp-helper
  rwxr-xr-x    root   41 KiB  Fri Nov 10 23:16:52 2017    nm-dispatcher
  rwxr-xr-x    root  899 KiB  Fri Nov 10 23:16:52 2017    nm-iface-helper
  rwxr-xr-x    root   21 KiB  Thu Oct  5 12:55:19 2017  
nm-openvpn-auth-dialog
  rwxr-xr-x    root   49 KiB  Thu Oct  5 12:55:19 2017  
nm-openvpn-service
  rwxr-xr-x    root   21 KiB  Thu Oct  5 12:55:19 2017  
nm-openvpn-service-openvpn-helper
  rwxr-xr-x    root    4 KiB  Tue Nov 14 09:07:25 2017    ./
  rwxr-xr-x    root  144 KiB  Fri Nov 17 08:09:42 2017    ../
  rwxr-xr-x    root    4 KiB  Tue Nov 14 09:07:25 2017    conf.d/
  rwxr-xr-x    root    4 KiB  Thu Oct 12 09:14:14 2017    VPN/

   Found 22 contents in directory /usr/lib/NetworkManager

Folders : 4
Recognized files : 0
Unrecognized files : 18

**Comment by besser82** [comment]
I checked a bit deeper into that problem and isolated a [change in openvn-gnome](https://github.com/NetworkManager/network-manager-openvpn/commit/dbfedc83688ffa0db641fdfafc997fa651178016#diff-ab51fb04301fe8ecb2b4812db567dd80L510) that causes this problem.

@leigh123linux I'll see, if there is a way, how we can get that fixed…

**Comment by besser82** [comment]
I didn't find a real cause nor solution for this, yet…  But we discovered a workaround:

1. open network panel
2. go to wifi, make sure it's enabled and click `connect ot hidden network`
3. in the new window click on `Abort`
4. optional: you can disable wifi again, if you wish
5. click on `+` and then openvpn
6. the editor window appears as expected

@presianbg I hope that saves you until we got a working fix.

**Comment by besser82** [comment]
@presianbg Issue should be fixed in the PR above.

**Comment by presianbg** [comment]
@besser82 Many thanks :)

**Comment by besser82** [comment]
Let's hope @clefebvre will merge it fast.
