### ISSUE TITLE
cinnamon-settings network don't allow to connect to pppoe

### ISSUE THREAD

**Issue by Shatur95** [linuxmint/cinnamon-control-center#186]
```
 * Cinnamon version - 3.6.3
 * Distribution - Arch
 * 64 bit
 ```
**Issue**
With new version of NetworkManager (1.10) pppoe connections doesn't work.
I added pppoe connection:
<a target="_blank" href="https://itmages.ru/image/view/6264592/3dbf2cec"><img src="http://storage3.static.itmages.ru/i/17/1118/s_1511002495_8352762_3dbf2cec05.png" /></a>
But I can't connect to it from GUI. When I enable cable connection I automatically connect to Ethernet connection:
<a target="_blank" href="https://itmages.ru/image/view/6264598/2ec2d784"><img src="http://storage9.static.itmages.ru/i/17/1118/s_1511002805_1573044_2ec2d7848e.png" /></a>
Also when I launching `cinnamon-settings network` with this Ethernet connection, I have some warnings in console:
```
$ cinnamon-settings network

(cinnamon-settings.py:6369): network-cc-panel-WARNING **: Error connecting to ModemManager: Ошибка вызова StartServiceByName для org.freedesktop.ModemManager1: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.freedesktop.ModemManager1.service not found.
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_get_type: assertion 'value != NULL' failed
  Gtk.main()
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
  Gtk.main()
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:612: Warning: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
  Gtk.main()
```
Also when I'm connected to pppoe (which I connected via CLI), cinnamon-settings crashes:
```
$ cinnamon-settings network
(cinnamon-settings.py:14696): network-cc-panel-WARNING **: Error connecting to ModemManager: Ошибка вызова StartServiceByName для org.freedesktop.ModemManager1: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit dbus-org.freedesktop.ModemManager1.service not found.
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:148: Warning: g_object_get_is_valid_property: object class 'NMDevicePpp' has no property named 'hw-address'
  self.main_stack.set_visible_child_name("content_box_page")
*** Error in `/usr/bin/python2': double free or corruption (out): 0x00007fff8f77fb90 ***
Аварийный останов (стек памяти сброшен на диск)
```
I think that caused by changes in new NetworkManager.

**Comment by leigh123linux** [comment]
We're not interested in the output for cinnamon-settings network
Post the output for this instead.

```
cinnamon-control-center -v  network
```

**Comment by Shatur95** [comment]
Hm... I'm sorry but my distro don't provide 'cinnamon-control-center' in [this](https://www.archlinux.org/packages/community/x86_64/cinnamon-control-center/) package.
