### ISSUE TITLE
Cinnamon-control-center 3.6.5-1 does not work

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon-control-center#193]
```

    Cinnamon version 3.6.4-1
    Distribution - Arch
    Graphics hardware and driver used: Intel
    64 bit

```

**Issue**
cinnamon-control-center 3.6.5-1 does not work. Cannot access settings on Archlinux x64.
No problems on the version 3.6.3-1.

**Steps to reproduce**

**Expected behaviour**

**Other information** 
in terminal: 'Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 45, in <module>
    modules = map(__import__, mod_files)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_sound.py", line 689
    icon = iconTheme.load_icon("bluetooth", 32, 0)
       ^
IndentationError: expected an indented block'

**Comment by mtwebster** [comment]
Ok turns out this should have been in cinnamon after all, there was a cinnamon-control-center update as well, but is unrelated to this.  It's fixed an a new update (cinnamon 3.6.5) release already, sorry.

https://github.com/linuxmint/Cinnamon/issues/7055
