### ISSUE TITLE
Applets/Extensions: UX Issues

### ISSUE THREAD

**Issue by fllp** [linuxmint/cinnamon-control-center#196]
```
 * cinnamon-control-center 3.6.5
 * Mint 18.3
 * Intel integrated (modeset drivers)
 * 64 bit
 ```

**Issue**

The new controls for managing applets, extensions, desktlets and themes have a few issues regarding usability/UX.

1. before LM 18.3 it was possible to right click on an entry and remove, add or uinstall from the context menu. Now the item has to be first selected and the button for the desired action has to be selected.
1. some of the icons used are not particularly clear regarding their purpose. Specifically this concerns:
    - *download*: this should be something like `go-bottom-symbolic` instead of `go-down`/`down` in order to match the common design scheme of download buttons (i.e. like Firefox, Chrome, Material Icons)
    - icons for *update all* and singular *update* in download list are inconsistent
    - maybe discriminating between applets/desktlets and extensions is feasible. The icons ( `+`, `-`) are used to both designate *add*/*remove* and *enable*/*disable*
    - *uninstall*: maybe using the (colored) `remove` instead of current white on black circled icon is more fitting

In general it might be a good idea to implement actions like *add*, *remove*, *uninstall* a.s.o. as 'inline' actions, being available to the rightmost of the selected item. The central controls at the window bottom feel a bit cumbersome to interact with.

Also, when using different icon themes the buttons might look even more out of place. The Numix icon theme for example uses simplistic angular arrows for `go-down`. This makes the download button for applets/extensions/... look like dropdown menus.

If desired, I can add screenshots/icon samples.

**Comment by leigh123linux** [comment]
Cinnamon-settings (cinnamon) manages applets, extensions, desktlets and themes.

**Comment by fllp** [comment]
Oh I see. Pardon me then :)
