### ISSUE TITLE
Privacy Settings: allow disabling of build-in webcam & microphone

### ISSUE THREAD

**Issue by GitHubIsToxic** [linuxmint/cinnamon-control-center#198]
The ability to disable a computer build-in webcam and microphone should be a core privacy setting. Even the privacy nightmare that is Windows 10 acknowledges this.
For example, the new Skype client (v8.x) for Linux should not be able to access the webcam and microphone.

This should be fairly easy to implement by modifying /etc/modprobe.d/blacklist.conf via the privacy settings panel. Cinnamon currently lacks a CLI-free solution.

Thanks!

**Comment by leigh123linux** [comment]
I will veto any solution using modprobe blacklisting as it is a crappy solution.
