### ISSUE TITLE
Can't copy the system information with information about a system in cinnamon settings.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon-control-center#199]
```
 * Cinnamon version (3.6.7)
 * Distribution - Mint 18.3
 ```

**Issue**
Cinnamon system settings in information about the system do not allow to copy primary information in the labels.

**Steps to reproduce**
Try to copy a text in a label.

**Expected behaviour**
You should be able to copy this information for your comfort.

**Other information**
![inform](https://user-images.githubusercontent.com/23406555/34454669-61fb8c60-ed70-11e7-8730-62a0a003849e.png)

**Comment by leigh123linux** [comment]
Please report the issue against cinnamon
