### ISSUE TITLE
[Suggestion][Minor] Rename "Sound Effects" tab to "Notification Sounds"

### ISSUE THREAD

**Issue by msasad** [linuxmint/cinnamon-control-center#202]
```
 * cinnamon-control-center version
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**
The phrase "Sound Effects" usually gives the perception of effects that can be added to sounds. For example echo or reverb. Thus, the sound effects tab in sound settings can be renamed to something like "Notification Sounds" as this tab deals with notification sounds used in Cinnamon.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by clefebvre** [comment]
Many thanks for contributing to Cinnamon. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
