### ISSUE TITLE
No option to change time/date locale via GUI

### ISSUE THREAD

**Issue by AvantR** [linuxmint/cinnamon-control-center#214]
**Issue**
There is no way to change time/date locale via GUI because "time and date" is in the wrong place.

**Expected behaviour**
A way to change "time/date" locale to match with the rest localization.

**Possible solutions**
1. Move "time and date" in "Region" where it belongs, since it's related to locale and not to interface language.
2. Make it more configurable like other Desktop environments

![mintlocale](https://user-images.githubusercontent.com/40040810/45937256-2c740c00-bfc7-11e8-9ecb-fd754b962ff6.png)

**Comment by leigh123linux** [comment]
Many thanks for contributing to cinnamon-control-center. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by AvantR** [comment]
> Time/date format is dictacted by LC_TIME but so are the name of the days/months. Setting an LC_TIME that is different than LANGUAGE results in incorrect dates.

Yes I know that LC_TIME is both for time and date (days, months, years) but why the results incorrect?

Could you please give an example in practice because not only any other Desktop environment does what I say by default, even if you use cinnamon on ubuntu or fedora if I recall correctly, without being sure, I think it uses gnome-language-selector by default but also I can do this if I set my preferred language in that var but that's not an elegant way.

Look at the following, it's from ubuntu and it was generated automatically. When I change locale lang, it also changes LC_TIME
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=it_IT.UTF-8
LC_TIME=it_IT.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=it_IT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=it_IT.UTF-8
LC_NAME=it_IT.UTF-8
LC_ADDRESS=it_IT.UTF-8
LC_TELEPHONE=it_IT.UTF-8
LC_MEASUREMENT=it_IT.UTF-8
LC_IDENTIFICATION=it_IT.UTF-8
LC_ALL=
```

**Comment by AvantR** [comment]
> I misread this the first time, mintlocale isn't part of cinnamon-control-center

Sorry for that, I'm new to cinnamon and I thought it was a builtin module of the settings app
