### ISSUE TITLE
Printers panel doesn't work properly with modern wifi printers

### ISSUE THREAD

**Issue by Motherboard** [linuxmint/cinnamon-control-center#217]
```
 * cinnamon-control-center version - Cinnamon 4.0.9 ?
 * Distribution - Mint 19.1
 * NVIDIA GP102 [GeForce GTX 1080 Ti] vendor: Gigabyte driver: nvidia v: 390.77 
 * 64 bit
 ```

**Issue**
Canon iP2750 isn't shown in the Printers panel, clicking on add and expanding the network options - it is shown, but when trying to add it (either driverless IPP, LPD via DNS-SD or IPP via DNS-SD) it gives an error about CUPS internal error.
`$ lpstat -l -e` gives
`Canon_iP7200_series network none ipp://Canon%20iP7200%20series._ipp._tcp.local/`
So the system does see it, and `lp -d Canon_iP7200_series /etc/nsswitch.conf` does print (and for a minute the printer is shown in the Printers panel - but then disappears). 

On Mint 17.3, I was able to add this printer.

**Steps to reproduce**
* Have Canon iP2750 configured and accessible in your wifi network
* Open the Printers panel

**Expected behaviour**
Show the printer in the Printers panel, as the system sees it and prints to it just fine without the need to install anything.

**Other information**

**Comment by leigh123linux** [comment]
Please file the issue against system-config-printer package at Ubuntu bug tracker.
