### ISSUE TITLE
It is too hard to find the HiDPI setting, at least when, because one has yet to find it, everything is very small! (Suggested fix included.)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-control-center#218]
```
 * cinnamon-control-center version: 4.0.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19.1
 * Graphics hardware *and* driver used: NA
 * 32 or 64 bit: 64
 ```

**Issue**

> I spent almost 20 minutes trying to figure out how to configure scaling on my HiDPI monitor as everything looked tiny and I had to use a magnifying glass. Wisdom says anything related to monitor or display should be listed under ‘Display’ tab. Nope. I found it was buried under ‘General’ tab. Why?
([Source](https://www.tfir.io/critical-review-of-linux-mint-19-2/).)

**Steps to reproduce**

Have everything too small (on those machines that need the HiDPI setting enabled but where Mint does not enable that setting automatically). Try and fail to find the HiDPI setting under 'display'.

**Expected behaviour**

Ideally (1) HiDPI should be enabled for screens at by default. Failing that, (2) Mint - or the installer - could at least ask the user about turning in on. Irrespective of all that, but all the more important is neither 1 nor 2 are implemented: (3) put an icon for HiDPI under 'display'. Also, (4) 'dpi' and 'hidpi', as search terms in the Settings window, should find the setting. (What is the use of having a search otherwise?)

**Other information**

If this is the wrong place to file this report, then I am sorry. (It seems to me hard to know sometimes what should be filed where.)

**Comment by icarter09** [comment]
@LinuxOnTheDesktop are you still experiencing this issue?

**Comment by LinuxOnTheDesktop** [comment]
No, I'm not. Here is why. On Mint 19.3, the Hi-DPI setting has been moved to where one expects it to be, namely under 'display' (albeit not under the tab that shows initially). On Mint 20 beta, the same is true (and indeed the scaling options are now the first things one sees under 'Display').
