### ISSUE TITLE
Display settings UI broken for Hi-DPI monitors in 4.6.0

### ISSUE THREAD

**Issue by ohell** [linuxmint/cinnamon-control-center#234]
```
 * 4.6.0-1
 * Arch (Manjaro Linux)
 * Intel Corporation Iris Graphics 6100, 
 * 64 bit
 ```

The new UI ignores base-scaling setting, causing poor resolution on Hi-DPI display. 

**Steps to reproduce**
Setting base-scaling as 2x has no effect, and reopening the UI shows it reset to 'Normal'

**Expected behaviour**
scaling factor setting should be effective

**Other information**
I am opening this issue here because the display setting UI changed between 4.4 and 4.6, and the lack of scaling being applied seems to indicate it is an issue with control center rather that settings daemon.

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/cinnamon/issues/9315
