### ISSUE TITLE
Dev package: Lack of header files

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon-control-center#253]
Only about 3 header files are installed with the dev package, cc-editable-entry.h, cc-panel.h and cc-shell.h

There are some more header files installed in other DE's, for example gdm-languages.h (known as mate or gnome-languages.h) that aren't installed. And most likely there are more.

Possible subtask, I figured open this instead of presume only 1 file is missing.

Updating Meson Builds should probably fix this.

**Comment by leigh123linux** [comment]
Does any package actually require these header to compile?

**Comment by ItzSwirlz** [comment]
Well let's just say I may be doing something... (trust me for you as a Cinnamon Fedora Maintainer you may like this) and gdm-languages.h is the closest I can find to gnome-languages.h to compile.

![Screenshot from 2020-11-23 22-38-01](https://user-images.githubusercontent.com/24401303/100101404-30fb1000-2e30-11eb-829f-64a1ff83a06d.png)

But still-keep in mind that **presumably** you won't know who's doing what-so assuming that the header file is not heavy and dependent on other header files, I think it's fine, but for all I know, /shrug

The above image is a private repo, let me know if you want me to add you to it to see it better.

**Comment by mtwebster** [comment]
The library package is only used internally, I may just remove it and libcinnamon-control-center-dev, so maybe leave it be for the moment

**Comment by ItzSwirlz** [comment]
It's also possible we can move it to libcinnamon-desktop-dev as always

**Comment by ItzSwirlz** [comment]
Some packages I'm seeing it's just header files that are ones that don't depend on itself, some are just all the header files bundled in one... I think for now leave this on standby and just to make me happy (for now and for a while, and also to see if maybe there can be some sort of a 4.8.0 cinnamon-initial-setup release?) just bundle gdm-languages.h and call it a day for now. I'll also make https://github.com/Ubuntu-Cinnamon-Remix/cinnamon-initial-setup public. Thoughts? Yay or Nay

**Comment by ItzSwirlz** [comment]
So while this can be another issue, the main issue I have is that gdm-languages.h should also have an update.. I'll likely open up another issue for that.

**Comment by ItzSwirlz** [comment]
So in the case of gdm-languages.h:

It's quite outdated-but to try and force through upstream Shell code through Cinnamon which has nothing to do with the physical DE and could ruin stuff, in the case we need to, lets come back to this.

cinnamon-initial-setup will be stuck with using it's own libraries when it should be used upstream-but for now, let's just deal with it, and move on. Best for all, let's come back to this later.
