### ISSUE TITLE
Devel Discussion: Move cinnamon-settings into this repository for next major release

### ISSUE THREAD

**Issue by ItzSwirlz** [linuxmint/cinnamon-control-center#255]
Hello everyone,

Don't worry about this issue until the Mint 20.1 Bug Squash Rush is over- this is just for future Cinnamon, whether its 4.10.0 or 5.0, yeah...

So cinnamon-settings has been stuck and divided-cinnamon settings is part of the cinnamon package but some important modules remain here in cinnamon-control-center and haven't been ported to Python yet, most likely because there is no Python wrapper for it.

Everyone has had the idea that we all know of-**one of them has to go.** It is confusing for developers and just **has** to stop.

So, here is my idea. This is much better than removing the cinnamon-control-center package as then downgrades won't be too challenging and Cinnamon can remain to be core cinnamon, and not just like 90% of the whole entire desktop.

Move cinnamon-settings into this repository. We can keep the Python code-no letting old work go to waste, and Python is much more easier to maintain and it will genuinely  help us, but it also keeps us more organized. 

This would become a project similar to mintdesktop or mate-tweak. Meson would continue to be used and the idea is we merge cinnamon-settings with cinnamon-control-center. This also ensures stability for the most important settings modules which are already written in C.

cinnamon-settings is also a weird name-we already have cinnamon-control-center. If you just ran 'cinnamon-control-center' you would get only 4 modules-which are all integrated in with cinnamon-settings. Awkward. But one has a C frontend and the other has a Python frontend?

Anyways, cinnamon-settings if this were to be moved here and less the load on cinnamon's repo we should rename cinnamon-settings to cinnamon-control-center. This keeps it more organized and neat for everyone and developers from other places like MATE to help and find the correct cinnamon-settings as well.

I suggest keep it mostly Python based, Python UI with most modules Python but keep some C modules until we port them for now.

I know this will get lots of criticism, but this is just my idea to avoid confusion while solving the problem-one has to go, and it should be move cinnamon-settings here and rename it.

**Comment by mtwebster** [comment]
We've been trying to move everything to cinnamon over time. The goal is to be rid of this package altogether. There's a great deal of integration within cinnamon, settings, and various apps and utilities, and keeping things in the cinnamon package helps further  that effort.

Most users won't open settings from a terminal, they'll look in the menu for whatever their issue is (or just System Settings) and spawn whatever they need there. They don't care what program they're running (and cinnamon-control-center isn't in the menu). Arguably, we could stop shipping cinnamon-control-center (the program, not the actual modules it supplies) but like I said, 99% of people never know it's there, anyhow.

The remaining modules there are fairly complex and no one has had the inclination (or more likely, time) to do any more work on this lately, but there really isn't a lot of urgency for this
