### ISSUE TITLE
Renaming the boot drive "Linux Mint"

### ISSUE THREAD

**Issue by Jimbo-Jim** [linuxmint/cinnamon-control-center#267]
I've noticed in the past that some Ubuntu based distributions rename the boot drive from "Ubuntu" to their distribution name. So, if you were dual booting for example you'd no longer see Ubuntu listed as the boot drive, instead you'd see "Linux Mint". Just thought this would be a cool change to make in the future.

**Comment by leigh123linux** [comment]
File the request against linuxmint.

https://github.com/linuxmint/linuxmint/issues
