### ISSUE TITLE
Region & Language menu item in Preferences has wrong option

### ISSUE THREAD

**Issue by cbv-wizzdom** [linuxmint/cinnamon-control-center#268]
```
 * Ciinnamon version 4.8 Ulyssa and 5.0.4+Uma
 * Distribution - Mint 20.1, 20.2
 * Graphics hardware *and* driver used (Irrelevant)
 * 64 bit

 ```

**Issue**
Region & Language item in Preferences displays "System Settings"

**Steps to reproduce**
Use menu editor to make Region & Language visible
Use Menu to activate Region and Language in Preferences

**Expected behaviour**
Setting window for region and language opens

**Other information**

Menu item for Region & Language has parameter "region" instead of "language"

**Comment by mtwebster** [comment]
Removed: https://github.com/linuxmint/cinnamon-control-center/commit/3950c3b647587ec908e35319e226e56ae086b484

@cbv-wizzdom: You'll have to delete `~/.local/share/applications/cinnamon-region-panel.desktop` yourself if it exists. (this was created when you turned it on in the menu editor)
