### ISSUE TITLE
If the Printers fails to open, then the user should be told why

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-control-center#277]
```
 * cinnamon-control-center version: 5.2.1
 * Distribution: Mint 20.3
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

Settings -> Printers hangs (or rather it hangs on one and only one of those of my PCs that run Linux Mint Cinnamon).

In a terminal (and again only of the affected PC):

```
$ system-config-printer
Traceback (most recent call last):
  File "/usr/share/system-config-printer/system-config-printer.py", line 29, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

**Steps to reproduce**

As above.

**Expected behaviour**

No hang in the GUI but rather an error message.

**Other information**

- Please move this issue if I have misfiled it.
- Please delete this issue if I have submitted it twice. (I thought that I had submitted it, and yet it seemed I had not; so I recreated the report.)
- I would not mind being told of a fix. Still, perhaps the real problem here is the lack of an error message in the GUI. That said: perhaps something - some sort of Python version check? - would and should stop the problem arising in the first place.

**Comment by leigh123linux** [comment]
You need to report it to ubuntu.

https://launchpad.net/ubuntu/+source/system-config-printer/+bugs

**Comment by LinuxOnTheDesktop** [comment]
[Done](https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1963723).

**Comment by LinuxOnTheDesktop** [comment]
`sudo apt-get install --reinstall python3-dbus` allowed the applet (if 'applet' is the word I want) to open. (Once it had opened, I had a bad experience trying to get the 'cups' service started. I had to do so via a terminal.)
