### ISSUE TITLE
Please tell me what this line means(translate issue)

### ISSUE THREAD

**Issue by bdh1993** [linuxmint/cinnamon-control-center#283]
```
 * cinnamon-control-center version : 5.0.2+uma
 * Distribution : Linuxmint 20.2
 * 64 bit
 ```

**Issue**
It is a problem that cannot be translated even though it is added to the translation file.

The word "Metric"

1. Is there a reason to use "network parameters"?
- I don't understand because the method of use is different from other "gtk_label_new".
2. How can I translate "Metric" normally?
- Is there a way to translate it if I use it as it is?

**Steps to reproduce**

1. go to folder
/usr/share/locale/@@/LC_MESSAGES/cinnamon-control-center.mo

2. change mo to po
msgunfmt cinnamon-control-center.mo -o cinnamon-control-center.po

5. added the translate
msgid "Metric"
msgstr "translate the message"

6. chage po to mo
msgfmt cinnamon-control-center.po -o cinnamon-control-center.mo

7. check the translate
network settings Ipv4 & Ipv6
![image](https://user-images.githubusercontent.com/58254473/172771162-3477a736-59e8-4faa-ba3c-60592df9c351.png)
**not changed**

8. change source
panels > network > connection-editor > ce-page-ip4.c
https://github.com/linuxmint/cinnamon-control-center/blob/a63cfb5979f57bb272375a02c1983175463d637e/panels/network/connection-editor/ce-page-ip4.c#L501
panels > network > connection-editor > ce-page-ip6.c
https://github.com/linuxmint/cinnamon-control-center/blob/a63cfb5979f57bb272375a02c1983175463d637e/panels/network/connection-editor/ce-page-ip6.c#L467

Original : label = gtk_label_new (C_("network parameters", "Metric"));
Changed : label = gtk_label_new (_("Metric"));
![image](https://user-images.githubusercontent.com/58254473/172771672-1693d803-de30-4267-85f8-f8a0399d399e.png)

9. step 2, 3, 4, 5
**"is changed"**

**Comment by ItzSwirlz** [comment]
You would want to find "Metrics" in the language you want to translate-try a English-(Lang) dictionary or WordReference.

Translations are also done at https://translations.launchpad.net/linuxmint/latest/

**Comment by mtwebster** [comment]
Hi, the connection editor files where these strings are weren't being included. This is probably why they're not translatable - there's no original Msgid for that (and other) strings.

From what I understand about localization, the 'network parameters' string is a context for translation - you might be using "Metric" in some other place where it could mean something different, or the language being localized has a different word for that particular use case. Without the context string, it would use the same string in both places (and will appear in the potfile only once).

Once we regenerate the potfile they'll end up on [Launchpad](https://translations.launchpad.net/linuxmint/latest).

Thanks for catching this.

**Comment by bdh1993** [comment]
Thanks you for your help :)

I found how to fill out the PO file.
![image](https://user-images.githubusercontent.com/58254473/173740290-1e022a64-59b5-4fdd-9a9d-e265ef5c2a3b.png)

![image](https://user-images.githubusercontent.com/58254473/173740350-87941e31-aa56-4152-88ca-357533a45383.png)

There were some missing translations in the PO file, but I didn't know how to translate them.

The "Metric" word was translated only when the "network parameter" was specified using msgctxt.
