### ISSUE TITLE
Symlinking desktop files fail when certain options disabled

### ISSUE THREAD

**Issue by vishwin** [linuxmint/cinnamon-control-center#289]
```
 * latest git
 * any, but running FreeBSD
 * Intel modesetting
 * amd64
 ```

**Issue**
Especially after ca95ce7dfc4872ecef88b0074d2bee8f097d0394, because the four desktop files are hardcoded in `meson.build`, symlinking fails when any of the `color`, `networkmanager` or `wacom` options are disabled, because the relevant desktop file was never built or staged.

**Steps to reproduce**
Build and install from source as normal, but disable any of the `color`, `networkmanager` or `wacom` options ie `-Dcolor=false`

**Expected behaviour**
Only the options enabled in meson have desktop files symlinked.

**Other information**

**Comment by eli-schwartz** [comment]
The fallback on `install-scripts/desktop-file-links.py` would simply run `subprocess.call(['ln', '-s', ...])` for every single one, which didn't bother to check if it fails. When I contributed commit ca95ce7dfc4872ecef88b0074d2bee8f097d0394 I transcribed the symlinking file but neglected to check whether it was optional to install them. It should be simple enough to check the options first.
