### ISSUE TITLE
Can't specify keyboard layout shortcuts using 'keyboard' branch

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-control-center#29]
After updating to gnome-3.9 libs I was forced to switch on 'keyboard' branch of c-s-d. I applied appropriated changes to c-c-c(from 'keyboard' branch), but I still can't specify  keyboard layout shortcuts using c-c-c.

**Comment by leigh123linux** [comment]
Is this issue fixed?, if so please close.
