### ISSUE TITLE
[tablet] Can't assign clic action to a tablet button in map button

### ISSUE THREAD

**Issue by coolibry** [linuxmint/cinnamon-control-center#292]
```
 * cinnamon-control-center 5.4.3-1
 * Distribution : Archlinux with kernel 5.17.15-1-MANJARO
 * Graphics hardware : Ryzen 5600u
 * Tablet : Wacom BambooPT 2FG
 * 64 bit
 ```

**Issue**
in wacom settings >  map button, 
it's not possible to assign button to key but not to mouse clic (left / middle / right)  
on lightdm login all button works  as mouse (defined in wacom driver)
when cinnamon is launched if button action type = none,
we don't get default mouse clic

**Expected behaviour**
if no settings about button map,
then use default action from wacom driver 

**Other information**
we try to rebuild  :
- cinnamon-control-center and disable wacom support with :
`-Dwacom=false`
- rebuild cinnamon-settings-daemon and  disable wacom support with :
`-Duse_wacom=disabled`
all i can get is no action when i press button when cinnamon is run,
in lightdm login screen all is ok
with xev i don't have any event from button

**Comment by mtwebster** [comment]
Fixed (with exception of the 'help overlay' for now:
https://github.com/linuxmint/cinnamon-control-center/commit/23ba1437a5e5375cb6243dee1110cd766746bc3f
https://github.com/linuxmint/muffin/commit/9340e975249ec61e64c69b10d039444c9f4d7be2
https://github.com/linuxmint/cinnamon-settings-daemon/commit/88e9de536db46ed1bda3777d24e9305d694099c6
