### ISSUE TITLE
Add option: Disable file manager handling the desktop

### ISSUE THREAD

**Issue by spectas** [linuxmint/cinnamon-control-center#30]
Hi everybody,

I would like to have an option added to Cinnamon Control Center to disable the file manager handling the desktop. This was a useful option in Gnome I think, to prevent other users from "soiling" your desktop with files. E.g. people tend to save PDFs to the desktop, just to print them once and then leave it there.

Technically it seems to be the option "show-desktop-icons" in dconf's path org > nemo > desktop.

So what I would suggest concretely, is to add an option "Disable all icons" at the bottom of cinnamon settings' "Desktop" tab, which should be deactivated as default.

Kind regards,
Spectas

**Comment by leigh123linux** [comment]
cinnamon-settings desktop  has the option to disable all icons.
