### ISSUE TITLE
[Feature request] Please add power modes to Linux Mint inside the Power Management GUI

### ISSUE THREAD

**Issue by leonsk29** [linuxmint/cinnamon-control-center#322]
As the title says, please consider adding power modes to Linux Mint inside the Power Management GUI, something that lets users select between "High performance", "Balanced" and "Power saving", you get the idea. Windows has it. Other Linux distros have it, like Ubuntu, Zorin OS, Fedora and I'm sure others too, I think it would be a useful enhancement for the user experience of Linux Mint. Some time ago I posted this same feature request and another person told me it couldn't be done or that it would be too difficult, but if other distros are doing it, why Linux Mint can't? Thanks in advance and thanks again for all your hard work.

**Comment by clefebvre** [comment]
Thanks, we'll consider adding support in Cinnamon. Added to roadmap for the next release.

**Comment by rcalixte** [comment]
This is available as an applet already by the way: https://cinnamon-spices.linuxmint.com/applets/view/369.

**Comment by leonsk29** [comment]
> This is available as an applet already by the way: https://cinnamon-spices.linuxmint.com/applets/view/369.

Yes, I know, but I think a _native_ integration inside the OS interface would be a more elegant solution, as other distros are doing. Also, that applet doesn't come preinstalled by default, users need to explicitly search and install it.
