### ISSUE TITLE
Network Settings forget password for PEAP/MSCHAPv2 wireless authentication

### ISSUE THREAD

**Issue by m-oliver** [linuxmint/cinnamon-control-center#45]
The network settings configuration does not store the password when connecting to PEAP/MSCHAPv2 networks (e.g. eduroam which is widely used in academics).  It is possible to connect by typing in the password before each connect into the Wifi Security dialog.  The option  "Ask for this password every time" also does not work.  

This used to work when cinnamon was still using the Gnome control center for network configuration and got broken when cinnamon switched to its own.

I am using cinnamon on Fedora (current versions cinnamon-control-center-2.0.3-1.fc19, cinnamon-2.0.6-1.fc19, cinnamon-settings-daemon-2.0.5-1.fc19) and have been asked to file this upstream by the Fedora cinnamon maintainer.  This issue refers to Fedora bugzilla

https://bugzilla.redhat.com/show_bug.cgi?id=1019271

**Comment by NaKroTeK** [comment]
Same here with
```
> OS: Arch Linux x86_64
> Hostname: xxxxxxxxxxxx
> Uptime: 05 min, 51 sec
> Kernel: 4.2.5-1-ARCH
> Shell: /bin/bash
> Packages: 910
> WM: i3
> RAM: 1392M / 3746M (37%)
> CPU: Intel(R) Core(TM) i3 CPU M 370 @ 2.40GHz
> Root: 60G / 220G (29%) (ext4)
```

**Comment by icarter09** [comment]
@m-oliver is this still an issue for you?

**Comment by m-oliver** [comment]
Eduroam has been working reliably over many ytear now, so this issue has been solved.  Thanks!

**Comment by icarter09** [comment]
@m-oliver thanks for the update.
