### ISSUE TITLE
Network | Mobile Broadband: unable to delete a connection

### ISSUE THREAD

**Issue by rik-shaw** [linuxmint/cinnamon-control-center#48]
There appears to be no way to delete a mobile broadband connection.

"nm-connection-editor" is much more stable and all connections can be modified, created, and deleted consistently.  I think it best if this functionality (mainly to manage connections even if a modem not plugged in) would be beneficial.  See screen print from nm-connection-editor:
![screenshot from 2013-12-18 16 47 54](https://f.cloud.github.com/assets/2560632/1778567/71aaa790-6836-11e3-92d9-18388cbb2733.png)

**Comment by Tamir91** [comment]
@rik-shaw Hello, are you solved this problem?

**Comment by rik-shaw** [comment]
@Tamir91 Cinnamon includes both "Network Connections" (nm-connection-editor) and "Network Settings" (to the control center module) when you click on the network icon in the panel.  So yes it is "solved" just because @clefebvre made sure to include both tools for full functionality.
