### ISSUE TITLE
[Display] Monitor frequency cannot be changed

### ISSUE THREAD

**Issue by shred** [linuxmint/cinnamon-control-center#55]
The Display settings tool should have a selection box to configure the monitor frequency.

Rationale: By default, the maximum monitor frequency is used. For my TFT monitors, this is 60 Hz. This results in tearing effects when videos are played (which are usually played with 25 or 50 fps here). I could reduce this tearing if I was able to set the monitor frequency to 50 Hz.

**Comment by vladipus** [comment]
Want this feature as well. Seems like my TV's maximum refresh rate is not correctly detected, and I would like to set it explicitly. For now, I have to edit the `monitors.xml` file by hand.

**Comment by Lukypie** [comment]
Any updates on this?

**Comment by vladipus** [comment]
What's the status of this? Seems like a trivial thing to implement.

**Comment by pc-jedi** [comment]
@clefebvre Since you removed the feature from the [roadmap](https://github.com/linuxmint/Roadmap/commit/bb1e8cd298fabcee38688c39981c893d47f941ae#diff-04c6e90faac2675aa89e2176d2eec7d8L141) in 2017, is there any chance to still get it?

**Comment by Borderliner** [comment]
Literally one combo box to set the refresh rate.

**Comment by clefebvre** [comment]
@pc-jedi yes. I can't commit to it, but I won't oppose it either.

**Comment by arehtykitna** [comment]
Much needed for LMDE Cinnamon Control Centre too if possible

**Comment by leigh123linux** [comment]
Fixed in c-c-c-4.6.0
