### ISSUE TITLE
Screen Locker does not work except if manually activated - security bug

### ISSUE THREAD

**Issue by tonywhelan** [linuxmint/cinnamon-control-center#98]
LM 17.1 Cinnamon 64bit desktop. 
Under Screen Locker settings I tested "Lock the computer when inactive" set to "after 1 minute", and the screen came up with a "Locked" display after a minute. Set it to "after 5 minutes" and again it did same. But in each case pressing a key gave me access to the computer WITHOUTt a password being entered.

Then I tested with setting the power options to "Turn off the screen when inactive for 5 minutes". Under ScreenLocker settings I set "Lock the computer when inactive" to "Never", but set "Lock the computer when the screen turns off" to "Immediately". I also tried  "Lock the computer when the screen turns off after 15 seconds". In each case the Screen Locker failed to operate.

If I manually lock the screen with ALT CTRL L then the systemdoes  correctly ask me for my password when I try to use it. 

This is a security issue, needs fixing asap.

**Comment by leigh123linux** [comment]
You have mis-filed your issue, cinnamon-control-center has no part in this.
If it's still an issue try filing it against cinnamon-settings-daemon or cinnamon-screensaver instead.
